disabled_rules:
- trailing_whitespace
- identifier_name
- multiple_closures_with_trailing_closure
included:
excluded:
- Pods
- SNUYum/View/Helper/AppDelegate.swift
- SNUYum/View/Helper/SceneDelegate.swift
